version: '3.8'

services:
  #  db:
  #    image: mysql:8.4.2
  #    container_name: mysql
  #    environment:
  #      MYSQL_DATABASE: ninja_demo
  #      MYSQL_ROOT_PASSWORD: 123456
  #    ports:
  #      - "3306:3306"
  #    volumes:
  #      - db_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '8000:8000'
    #    depends_on:
    #      - db
    env_file:
      - .env # 引用 .env 文件

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '80:80'
    depends_on:
      - backend

#volumes:
#  db_data:

# 设置默认网络
networks:
  default:
    name: ninja_network
