# Generated by Django 4.2.13 on 2024-06-27 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        default="system",
                        help_text="创建人",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "updater",
                    models.CharField(
                        blank=True,
                        default="system",
                        help_text="修改人",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, help_text="修改时间", verbose_name="修改时间"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, help_text="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.CharField(default=0, help_text="是否删除", max_length=36),
                ),
                ("title", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "部门表",
                "db_table": "sys_department",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        default="system",
                        help_text="创建人",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "updater",
                    models.CharField(
                        blank=True,
                        default="system",
                        help_text="修改人",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, help_text="修改时间", verbose_name="修改时间"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, help_text="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.CharField(default=0, help_text="是否删除", max_length=36),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("birthdate", models.DateField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="employee.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "员工表",
                "db_table": "sys_employee",
            },
        ),
    ]
