# Generated by Django 4.2.13 on 2024-06-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="users",
            options={"verbose_name": "用户表"},
        ),
    ]
