# Generated by Django 4.2.13 on 2024-06-28 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0002_alter_users_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dept",
            name="parent",
        ),
    ]
