# Generated by Django 4.2.13 on 2024-06-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0003_remove_dept_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="type",
            field=models.IntegerField(default=1, verbose_name="菜单等级，一级二级等"),
        ),
    ]
