# Generated by Django 4.2.13 on 2024-06-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0004_alter_menu_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="icon",
            field=models.CharField(
                blank=True,
                default="ant-design:book-outlined",
                max_length=64,
                null=True,
                verbose_name="菜单图标",
            ),
        ),
    ]
