# Generated by Django 4.2.13 on 2024-06-28 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0005_alter_menu_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menubutton",
            name="menu",
            field=models.ForeignKey(
                db_constraint=False,
                help_text="关联菜单",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_button",
                to="rbac.menu",
                verbose_name="关联菜单",
            ),
        ),
    ]
