# Generated by Django 4.2.13 on 2024-06-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0007_remove_menu_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="order",
            field=models.IntegerField(
                blank=True, default=1, help_text="排序", null=True, verbose_name="排序"
            ),
        ),
    ]
