# Generated by Django 4.2.13 on 2024-06-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0010_alter_menubutton_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="icon",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                null=True,
                verbose_name="菜单图标",
            ),
        ),
    ]
