# Generated by Django 4.2.13 on 2024-07-03 18:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rbac", "0012_alter_menu_parent_alter_menubutton_menu"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menubutton",
            old_name="name",
            new_name="title",
        ),
    ]
