# Generated by Django 4.2.13 on 2024-07-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rbac", "0013_rename_name_menubutton_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="menubutton",
            name="type",
            field=models.IntegerField(default=3, verbose_name="菜单等级，3是按钮"),
        ),
    ]
