# Generated by Django 4.2.13 on 2024-07-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rbac", "0014_menubutton_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="menubutton",
            name="status",
            field=models.BooleanField(
                blank=True, default=True, help_text="按钮状态", verbose_name="按钮状态"
            ),
        ),
    ]
